# Generated by Django 6.1.1 on 2026-09-14 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(choices=[('amazon', 'Amazon'), ('apple', 'Apple / iTunes'), ('google_play', 'Google Play'), ('steam', 'Steam'), ('walmart', 'Walmart'), ('other', 'Other')], max_length=20)),
                ('card_code_hash', models.CharField(db_index=True, max_length=128)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offered_rate', models.DecimalField(decimal_places=4, help_text='Rate offered to user, e.g. 0.85 of face value', max_digits=6)),
                ('verified_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual redeemable value confirmed by reviewer/automated check', max_digits=12, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='giftcards/%Y/%m/')),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
