# Generated by Django 6.1.1 on 2026-09-14 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giftcards', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_giftcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcardsubmission',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='giftcard_submission', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='giftcardsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giftcard_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='giftcardsubmission',
            index=models.Index(fields=['card_code_hash'], name='giftcards_g_card_co_fedd1f_idx'),
        ),
    ]
