# Generated by Django 6.1.1 on 2026-09-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardsubmission',
            name='brand',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('apple', 'Apple / iTunes'), ('google_play', 'Google Play'), ('steam', 'Steam'), ('playstation', 'PlayStation'), ('xbox', 'Xbox'), ('razer_gold', 'Razer Gold'), ('walmart', 'Walmart'), ('target', 'Target'), ('ebay', 'eBay'), ('nike', 'Nike'), ('other', 'Other')], max_length=20),
        ),
    ]
