# Generated by Django 6.1.1 on 2026-09-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0003_alter_giftcardsubmission_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('amazon', 'Amazon'), ('apple', 'Apple / iTunes'), ('google_play', 'Google Play'), ('steam', 'Steam'), ('playstation', 'PlayStation'), ('xbox', 'Xbox'), ('razer_gold', 'Razer Gold'), ('walmart', 'Walmart'), ('target', 'Target'), ('ebay', 'eBay'), ('nike', 'Nike'), ('other', 'Other')], max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Payout rate as a fraction of face value, e.g. 0.85', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('amazon', 'Amazon'), ('apple', 'Apple / iTunes'), ('google_play', 'Google Play'), ('steam', 'Steam'), ('playstation', 'PlayStation'), ('xbox', 'Xbox'), ('razer_gold', 'Razer Gold'), ('walmart', 'Walmart'), ('target', 'Target'), ('ebay', 'eBay'), ('nike', 'Nike'), ('other', 'Other')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['brand', 'recorded_at'], name='giftcards_g_brand_d30c27_idx')],
            },
        ),
    ]
