# Generated by Django 6.1.1 on 2026-09-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0003_alter_giftcardsubmission_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardsubmission',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcardsubmission',
            name='redeemed_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What the reviewer actually redeemed from the card, in the card's own value units", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='giftcardsubmission',
            name='redemption_reference',
            field=models.CharField(blank=True, help_text='Order / receipt / balance reference from the redemption, for audit', max_length=100),
        ),
        migrations.AlterField(
            model_name='giftcardsubmission',
            name='verified_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The confirmed GHS PAYOUT for this card (redeemed_value x offered_rate). Set by the server when a reviewer approves — never typed in directly.', max_digits=12, null=True),
        ),
    ]
