# Generated by Django 6.1.1 on 2026-09-20 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0004_giftcardsubmission_redeemed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('shopping', 'Shopping & retail'), ('gaming', 'Gaming'), ('apps_entertainment', 'Apps & entertainment'), ('fashion_beauty', 'Fashion & beauty'), ('food_travel', 'Food & travel'), ('prepaid', 'Prepaid cards (Visa / Mastercard / Amex)')], max_length=24)),
                ('color_from', models.CharField(default='#565b6b', max_length=7)),
                ('color_to', models.CharField(default='#7a8194', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=1000, help_text='Lower shows first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='giftcardsubmission',
            name='card_currency',
            field=models.CharField(default='GHS', help_text='Currency the card is denominated in; face/redeemed values are in this', max_length=3),
        ),
        migrations.AlterField(
            model_name='giftcardsubmission',
            name='brand',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='giftcardsubmission',
            name='face_value',
            field=models.DecimalField(decimal_places=2, help_text='Declared value, in card_currency', max_digits=12),
        ),
        migrations.AlterField(
            model_name='giftcardsubmission',
            name='offered_rate',
            field=models.DecimalField(decimal_places=6, help_text='GHS paid per 1 unit of card_currency, locked from the subcategory at submission time. (Submissions from before subcategories existed used a 0.85 fraction of a GHS face value.)', max_digits=14),
        ),
        migrations.CreateModel(
            name='GiftCardSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=48)),
                ('name', models.CharField(help_text='What the seller sees, e.g. "USA · E-code"', max_length=80)),
                ('country', models.CharField(blank=True, help_text='ISO country code, "EU", or "GLOBAL"', max_length=8)),
                ('currency', models.CharField(help_text='Currency the card is denominated in, e.g. USD', max_length=3)),
                ('card_format', models.CharField(choices=[('physical', 'Physical card'), ('ecode', 'E-code / digital'), ('any', 'Physical or e-code')], default='any', max_length=10)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, help_text="GHS paid per 1 unit of the card's currency (e.g. 12.5 = GHS 12.50 for each USD). EMPTY = this subcategory is shown as unavailable until you set a rate.", max_digits=14, null=True)),
                ('rate_updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('allow_auto_payment', models.BooleanField(default=True, help_text='Untick for high-risk cards (open-loop prepaid Visa/Mastercard/Amex). Those are never auto-credited or auto-paid-out; an admin must settle them by hand.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1000)),
                ('help_text', models.CharField(blank=True, help_text='Shown to the seller under the dropdown', max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='giftcards.giftcardbrand')),
            ],
            options={
                'ordering': ['brand__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='giftcardsubmission',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='giftcards.giftcardsubcategory'),
        ),
        migrations.AddConstraint(
            model_name='giftcardsubcategory',
            constraint=models.UniqueConstraint(fields=('brand', 'slug'), name='unique_subcategory_slug_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='giftcardsubcategory',
            constraint=models.CheckConstraint(condition=models.Q(('rate__isnull', True), ('rate__gt', 0), _connector='OR'), name='giftcard_rate_positive'),
        ),
    ]
