# Generated by Django 6.1.1 on 2026-09-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("giftcards", "0006_seed_gift_card_catalog"),
        ("giftcards", "0006_flatten_giftcard_rates"),
    ]

    operations = []