# Generated by Django 6.1.1 on 2026-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0006_seed_gift_card_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardsubmission',
            name='card_code_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='giftcardsubmission',
            name='code_reveal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giftcardsubmission',
            name='code_wiped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
