# Generated by Django 6.1.1 on 2026-09-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0007_encrypted_card_codes'),
        ('giftcards', '0007_merge_20260920_0904'),
    ]

    operations = [
    ]
