# Generated by Django 6.1.1 on 2026-09-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0008_merge_20260920_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCardRate',
        ),
        migrations.RemoveIndex(
            model_name='giftcardratehistory',
            name='giftcards_g_brand_d30c27_idx',
        ),
        migrations.DeleteModel(
            name='GiftCardRateHistory',
        ),
    ]
