# Generated by Django 6.1.1 on 2026-09-22 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0009_remove_old_rate_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='giftcards/gallery/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='giftcards.giftcardsubmission')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
