# Generated by Django 6.1.1 on 2026-09-14 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('GHS', 'Ghanaian Cedi'), ('USDT', 'Tether'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('escrow_balance', models.DecimalField(decimal_places=8, default=0, help_text='Funds held pending verification, not yet spendable', max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
