# Generated by Django 6.1.1 on 2026-09-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghanaian Cedi'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('USDC', 'USD Coin'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('ADA', 'Cardano'), ('DOGE', 'Dogecoin'), ('LTC', 'Litecoin')], max_length=10),
        ),
    ]
