# Generated by Django 6.1.1 on 2026-09-14 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('crypto_deposit', 'Crypto Deposit'), ('crypto_trade', 'Crypto Trade'), ('giftcard_sale', 'Gift Card Sale'), ('fiat_payout', 'Fiat Payout')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('settled', 'Settled'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Compliance')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='e.g. Breet transaction ID, on-chain tx hash', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
