# Generated by Django 6.1.1 on 2026-09-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counter_wallet',
            field=models.ForeignKey(blank=True, help_text="Only set for two-sided moves like a crypto trade — the wallet value is PAID FROM. The paid amount lives in metadata['counter_amount']. Null for one-sided transactions (gift card sale, payout, deposit).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_transactions', to='wallets.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(help_text='The wallet that RECEIVES value from this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet'),
        ),
    ]
