# Generated by Django 6.1.1 on 2026-09-19 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_counter_wallet_alter_transaction_wallet'),
        ('wallets', '0003_wallet_wallet_balance_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ghs_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GHS-equivalent of `amount` at the moment the transaction was created. Set for money leaving/entering the platform so KYC limits can be summed in the database instead of re-pricing history.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('crypto_deposit', 'Crypto Deposit'), ('crypto_trade', 'Crypto Trade'), ('giftcard_sale', 'Gift Card Sale'), ('fiat_payout', 'Fiat Payout'), ('wallet_load', 'Wallet Load'), ('crypto_withdrawal', 'Crypto Withdrawal'), ('transfer_out', 'Transfer Sent'), ('transfer_in', 'Transfer Received')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', 'created_at'], name='transaction_user_id_5d39b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
    ]
