# Generated by Django 6.1.1 on 2026-09-20 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(db_index=True, max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(blank=True, max_length=255)),
                ('pin_set_at', models.DateTimeField(blank=True, null=True)),
                ('totp_secret_encrypted', models.TextField(blank=True)),
                ('totp_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('totp_last_step', models.BigIntegerField(default=0, help_text='Newest 30s step already used — blocks code replay')),
                ('money_out_blocked_until', models.DateTimeField(blank=True, help_text='Cooling-off after a password reset / PIN or 2FA change', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
