# Generated by Django 6.1.1 on 2026-09-21 23:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0003_kycsubmission'),
        ('giftcards', '0009_remove_old_rate_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_detection_enabled', models.BooleanField(default=True)),
                ('velocity_window_minutes', models.PositiveIntegerField(default=60)),
                ('velocity_max_transactions', models.PositiveIntegerField(default=5, help_text='Settled transactions within the window that trigger a VELOCITY flag.')),
                ('structuring_detection_enabled', models.BooleanField(default=True)),
                ('structuring_window_hours', models.PositiveIntegerField(default=24)),
                ('structuring_min_transaction_count', models.PositiveIntegerField(default=3, help_text='Minimum under-limit transactions before a STRUCTURING flag is considered.')),
                ('structuring_sum_threshold_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text="Flag once under-limit transactions in the window sum to this fraction of the user's daily limit.", max_digits=4)),
                ('kyc_assist_enabled', models.BooleanField(default=True)),
                ('giftcard_assist_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk & AI-assist settings',
                'verbose_name_plural': 'Risk & AI-assist settings',
            },
        ),
        migrations.CreateModel(
            name='GiftCardAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_brand', models.CharField(blank=True, max_length=100)),
                ('detected_value_text', models.CharField(blank=True, help_text='Value/denomination as read off the card, verbatim.', max_length=50)),
                ('consistency', models.CharField(choices=[('consistent', 'Matches what was declared'), ('mismatch', "Doesn't match what was declared"), ('unreadable', "Couldn't read the image"), ('not_assessed', 'Not assessed')], default='not_assessed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='giftcards.giftcardsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='KYCAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extracted_full_name', models.CharField(blank=True, max_length=150)),
                ('extracted_date_of_birth', models.CharField(blank=True, max_length=30)),
                ('name_matches', models.BooleanField(null=True)),
                ('dob_matches', models.BooleanField(null=True)),
                ('face_impression', models.CharField(choices=[('likely_match', 'Likely match'), ('uncertain', 'Uncertain'), ('likely_mismatch', 'Likely mismatch'), ('not_assessed', 'Not assessed')], default='not_assessed', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="The model's own brief note, shown to the reviewer as-is.")),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='compliance.kycsubmission')),
            ],
        ),
    ]
