# Generated by Django 6.1.1 on 2026-09-19 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0004_transaction_ghs_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loads_enabled', models.BooleanField(default=True)),
                ('withdrawals_enabled', models.BooleanField(default=True)),
                ('transfers_enabled', models.BooleanField(default=True)),
                ('withdrawal_auto_approve_max_ghs', models.DecimalField(decimal_places=2, default=0, help_text='Withdrawals up to this GHS-equivalent value skip manual review and are sent straight away. 0 = every withdrawal waits for an admin.', max_digits=12)),
                ('giftcard_auto_payment_enabled', models.BooleanField(default=False, help_text="When ON, approving a gift card (after the reviewer attests it was redeemed) credits the seller's wallet immediately — no separate 'settle' click.")),
                ('giftcard_auto_payout_max_ghs', models.DecimalField(decimal_places=2, default=0, help_text='For sellers who opted in: gift card proceeds up to this amount are also sent on to their saved mobile money account automatically. 0 = never auto-send (proceeds stay in the wallet).', max_digits=12)),
                ('auto_payout_destination_cooldown_hours', models.PositiveIntegerField(default=24, help_text="A newly saved payout account can't receive AUTOMATIC payouts until this many hours have passed. Blunts account-takeover cash-outs.")),
                ('manual_deposit_instructions', models.TextField(blank=True, help_text="Shown to a user who loads their wallet when no payment gateway is connected (e.g. 'Send to MTN MoMo 024XXXXXXX, name Wolbi …'). The user's load reference is appended automatically.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment settings',
                'verbose_name_plural': 'Payment settings',
            },
        ),
        migrations.CreateModel(
            name='PayoutDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('mobile_money', 'Mobile money')], default='mobile_money', max_length=20)),
                ('network', models.CharField(help_text='mtn / telecel / airteltigo', max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(help_text='Name the user gave for this account', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_payout_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payoutdestination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('GHS', 'Ghanaian Cedi'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('USDC', 'USD Coin'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('ADA', 'Cardano'), ('DOGE', 'Dogecoin'), ('LTC', 'Litecoin')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_scheduled_transfers', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='The sender-side transaction, once it has run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['run_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('GHS', 'Ghanaian Cedi'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('USDC', 'USD Coin'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('ADA', 'Cardano'), ('DOGE', 'Dogecoin'), ('LTC', 'Litecoin')], max_length=10)),
                ('network', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'currency', 'network'), name='unique_deposit_address_per_asset')],
            },
        ),
        migrations.AddConstraint(
            model_name='payoutdestination',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'kind', 'network', 'account_number'), name='unique_active_payout_destination'),
        ),
        migrations.AddIndex(
            model_name='scheduledtransfer',
            index=models.Index(fields=['status', 'run_at'], name='payments_sc_status_9003ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='scheduled_transfer_amount_positive'),
        ),
    ]
