# Generated by Django 6.1.1 on 2026-09-21 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_ghs_value_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('network', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, help_text='The wallet-load transaction, once it has run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['run_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('GHS', 'Ghanaian Cedi'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('USDC', 'USD Coin'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('ADA', 'Cardano'), ('DOGE', 'Dogecoin'), ('LTC', 'Litecoin')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('address', models.CharField(blank=True, help_text='Crypto withdrawals only.', max_length=200)),
                ('network', models.CharField(blank=True, max_length=20)),
                ('memo', models.CharField(blank=True, max_length=40)),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(blank=True, help_text='GHS withdrawals only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payoutdestination')),
                ('transaction', models.ForeignKey(blank=True, help_text='The withdrawal transaction, once it has run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['run_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledload',
            index=models.Index(fields=['status', 'run_at'], name='payments_sc_status_load_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledload',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='scheduled_load_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='scheduledwithdrawal',
            index=models.Index(fields=['status', 'run_at'], name='payments_sc_status_wd_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledwithdrawal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='scheduled_withdrawal_amount_positive'),
        ),
    ]
