# Generated by Django 6.1.1 on 2026-09-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_scheduledload_scheduledwithdrawal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduledload',
            new_name='payments_sc_status_3815cc_idx',
            old_name='payments_sc_status_load_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledwithdrawal',
            new_name='payments_sc_status_026ccf_idx',
            old_name='payments_sc_status_wd_idx',
        ),
    ]
