# Generated by Django 6.1.1 on 2026-09-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_payments_sc_status_load_idx_payments_sc_status_3815cc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_transfer_instructions',
            field=models.TextField(blank=True, help_text="Shown to a user who chooses 'Bank transfer' to load their wallet (e.g. account name/number/bank/branch). The user's load reference is appended automatically so staff can match the deposit. Editable here without a redeploy — update this the moment the company bank account changes."),
        ),
        migrations.AddField(
            model_name='payoutdestination',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Branch, if the user provided one', max_length=100),
        ),
        migrations.AddField(
            model_name='payoutdestination',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name (bank destinations only)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payoutdestination',
            name='account_number',
            field=models.CharField(help_text='Mobile money number, or bank account number', max_length=30),
        ),
        migrations.AlterField(
            model_name='payoutdestination',
            name='kind',
            field=models.CharField(choices=[('mobile_money', 'Mobile money'), ('bank', 'Bank account')], default='mobile_money', max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutdestination',
            name='network',
            field=models.CharField(blank=True, help_text='mtn / telecel / airteltigo (mobile money only)', max_length=20),
        ),
    ]
