# Generated by Django 6.1.1 on 2026-09-21 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('bot_active', 'Assistant handling'), ('escalated', 'Waiting for an agent'), ('admin_active', 'Agent handling'), ('resolved', 'Resolved')], default='bot_active', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('escalation_reason', models.CharField(blank=True, choices=[('user_requested', 'User asked for a human'), ('restricted_intent', 'Topic always routes to a human'), ('low_confidence', "Assistant couldn't resolve it"), ('manual', 'Escalated by staff')], max_length=30)),
                ('escalation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_support_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('admin', 'Admin')], max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportsession',
            index=models.Index(fields=['status', 'updated_at'], name='support_sup_status_6ca258_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsession',
            index=models.Index(fields=['user', 'status'], name='support_sup_user_id_387cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['session', 'created_at'], name='support_sup_session_eff067_idx'),
        ),
    ]
