# Generated by Django 6.1.1 on 2026-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsession',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
