# Generated by Django 6.1.1 on 2026-09-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USDT', 'Tether'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=10, unique=True)),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
