# Generated by Django 6.1.1 on 2026-09-16 22:02

from django.db import migrations, models


def backfill_initial_snapshot(apps, schema_editor):
    """
    Seed one history point per existing rate so the fluctuation chart
    isn't empty the moment this ships — every future admin edit adds
    a real one on top of it.
    """
    ExchangeRate = apps.get_model("exchange", "ExchangeRate")
    ExchangeRateHistory = apps.get_model("exchange", "ExchangeRateHistory")
    for rate in ExchangeRate.objects.all():
        ExchangeRateHistory.objects.create(
            currency=rate.currency,
            buy_rate=rate.buy_rate,
            sell_rate=rate.sell_rate,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_seed_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USDT', 'Tether'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=10)),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['currency', 'recorded_at'], name='exchange_ex_currenc_fe012e_idx')],
            },
        ),
        migrations.RunPython(backfill_initial_snapshot, noop_reverse),
    ]
