# Generated by Django 6.1.1 on 2026-09-17 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('id_type', models.CharField(choices=[('national_id', 'National ID (Ghana Card)'), ('passport', 'Passport'), ('voters_id', "Voter's ID"), ('drivers_license', "Driver's License")], max_length=20)),
                ('id_number', models.CharField(max_length=64)),
                ('id_document_front', models.ImageField(upload_to='kyc/%Y/%m/')),
                ('id_document_back', models.ImageField(blank=True, null=True, upload_to='kyc/%Y/%m/')),
                ('selfie', models.ImageField(upload_to='kyc/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
