# Generated by Django 6.1.1 on 2026-09-24 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_kycsubmission'),
        ('transactions', '0004_transaction_ghs_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['status', '-created_at'], name='compliance__status_65fdde_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['user', 'status'], name='compliance__user_id_3ee002_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='compliance__status_42ede1_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['user', 'status'], name='compliance__user_id_b83ddf_idx'),
        ),
    ]
